[package]
name = "sfu-client"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
bincode = "1.3.3"
serde = { version = "1.0.136", features = ["derive"] }
uuid = { version = "0.8.2", features = ["v4", "serde", "wasm-bindgen"] }
